### ISSUE TITLE
Restore downstream tests with mambabuild

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/jupyter_server-feedstock#111]
### Comment:

Both #110 and #109 are both failing on the downstreams due to conda errors like:

```
TEST START: /home/conda/feedstock_root/build_artifacts/pkg_cache/jupyterlab-3.5.2-pyhd8ed1ab_0.conda
Copying package to conda-build croot.  No packages otherwise alongside yours will be available unless you specify -c local.  To avoid this warning, your package must reside in a channel structure with platform-subfolders.  See more info on what a valid channel is at https://conda.io/docs/user-guide/tasks/create-custom-channels.html
WARNING:conda_build.build:Copying package to conda-build croot.  No packages otherwise alongside yours will be available unless you specify -c local.  To avoid this warning, your package must reside in a channel structure with platform-subfolders.  See more info on what a valid channel is at https://conda.io/docs/user-guide/tasks/create-custom-channels.html
Reloading output folder: /home/conda/feedstock_root/build_artifacts
Traceback (most recent call last):
  File "/opt/conda/bin/conda-mambabuild", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/boa/cli/mambabuild.py", line 256, in main
    call_conda_build(action, config)
  File "/opt/conda/lib/python3.10/site-packages/boa/cli/mambabuild.py", line 228, in call_conda_build
    result = api.build(
  File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 180, in build
    return build_tree(
  File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3149, in build_tree
    test(list(local_file.values())[0][0],
  File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2874, in test
    actions = environ.get_install_actions(metadata.config.test_prefix,
  File "/opt/conda/lib/python3.10/site-packages/boa/cli/mambabuild.py", line 124, in mamba_get_install_actions
    solver = _get_solver(channel_urls, subdir, output_folder)
  File "/opt/conda/lib/python3.10/site-packages/boa/cli/mambabuild.py", line 100, in _get_solver
    solver.replace_channels()
  File "/opt/conda/lib/python3.10/site-packages/boa/core/solver.py", line 177, in replace_channels
    self.local_repos[channelstr] = libmambapy.Repo(
RuntimeError: Could not read JSON repodata file (/home/conda/feedstock_root/build_artifacts/pkg_cache/cache/cf8a841c.json) parse error line 34: subdir mismatch
```

Probably going to just ship without testing the downstreams, but would be good to get this back.

**Comment by jaimergp** [comment]
I've seen this too [outside conda-forge](https://github.com/jaimergp-forge/conda-feedstock/actions/runs/3735963397/jobs/6339780255). Not sure if it's a `libmamba` parsing error or a bad JSON file. Does it happen if you [disable `mambabuild`](https://conda-forge.org/docs/maintainer/conda_forge_yml.html#build-with-mambabuild)?

**Comment by bollwyvl** [comment]
thanks @jaimergp, trying on #112...

**Comment by bollwyvl** [comment]
It does appear to get past that sticking point. Still have some other issues, but i think they are more easily debugged (downstream test dep drift)

**Comment by bollwyvl** [comment]
```
    jupyterlab_server:             2.16.5-pyhd8ed1ab_0       local      
    openapi-core:                  0.14.2-pyhd8ed1ab_0       conda-forge
    openapi-schema-validator:      0.3.4-pyhd8ed1ab_0        conda-forge
    openapi-spec-validator:        0.5.1-pyhd8ed1ab_0        conda-forge
```

Then

```
E   ImportError: cannot import name 'default_handlers' from 'openapi_spec_validator' ($PREFIX/lib/python3.11/site-packages/openapi_spec_validator/__init__.py)
```

**Comment by bollwyvl** [comment]
Ugh, that shouldn't be happening:

**Comment by bollwyvl** [comment]
Reopening as it _doesn't_ use `mambabuild`, and it would be ideal to get back to that.

**Comment by bollwyvl** [comment]
Changed this up to `rattler-build` after #161. 

Downstreams unsurprisingly don't work.

**Comment by bollwyvl** [comment]
`notebook` and `jupyterlab-server` are under test as of #165

**Comment by bollwyvl** [comment]
#174 has taken `notebook` and `jupyterlab-server` out until they are rebuilt for `python_min: 3.11`, despite the [docs](https://rattler-build.prefix.dev/latest/reference/recipe_file/#downstream-tests) saying:

> _Sometimes downstream packages do not resolve. In this case, the test is ignored_

```

Error: Downstream test with "/tmp/.tmpieBqbd/notebook-7.6.2-pyhcf101f3_0.conda" failed
 │ × error Downstream test with "/tmp/.tmpieBqbd/notebook-7.6.2-pyhcf101f3_0.conda" failed
 │
 ╰─────────────────── (took 5 seconds)
Error:   × Test failed
  ├─▶ failed to setup test environment
  ╰─▶ Cannot solve the request because of: The following packages are
      incompatible
      └─ notebook ==7.6.2 pyhcf101f3_0 cannot be installed because there are
      no viable options:
         ├─ notebook 7.6.2 would require
         │  └─ jupyter_server >=2.19.0,<3, which cannot be installed because
      there are no viable options:
         │     ├─ jupyter_server 2.21.1 would require
         │     │  └─ python >=3.11, for which no candidates were found.
         │     ├─ jupyter_server 2.21.1 is excluded because due to strict
      channel priority not using this option from: 'file:///tmp/.tmpmgKgU8/'
         │     ├─ jupyter_server 2.21.1 is excluded because due to strict
      channel priority not using this option from: 'file:///home/conda/
      feedstock_root/build_artifacts/'
         │     └─ jupyter_server 2.19.0 | 2.20.0 | 2.21.0 is excluded because
      due to strict channel priority not using this option from: 'https://
      conda.anaconda.org/conda-forge/'
         └─ notebook 7.6.2 is excluded because due to strict channel priority
      not using this option from: 'https://conda.anaconda.org/conda-forge/'
      

```
