### ISSUE TITLE
Python 3.6 not supported by version 1.13.2 anymore

### ISSUE THREAD

**Issue by spreiter** [conda-forge/jupyter_server-feedstock#90]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I am using Python 3.6 and tried to install jupyterlab after creating an environment with a file. But `jupyter_server` seems to be installed with the wrong version **1.13.2**, which is not supported by Python 3.6 anymore.

```
Traceback (most recent call last):
  File "/Users/Simon/miniconda3/envs/lab3/bin/jupyter-lab", line 6, in <module>
    from jupyterlab.labapp import main
  File "/Users/Simon/miniconda3/envs/lab3/lib/python3.6/site-packages/jupyterlab/labapp.py", line 13, in <module>
    from jupyter_server.serverapp import flags
  File "/Users/Simon/miniconda3/envs/lab3/lib/python3.6/site-packages/jupyter_server/serverapp.py", line 83, in <module>
    from jupyter_server.services.sessions.sessionmanager import SessionManager
  File "/Users/Simon/miniconda3/envs/lab3/lib/python3.6/site-packages/jupyter_server/services/sessions/sessionmanager.py", line 22, in <module>
    from jupyter_server.traittypes import InstanceFromClasses
  File "/Users/Simon/miniconda3/envs/lab3/lib/python3.6/site-packages/jupyter_server/traittypes.py", line 7, in <module>
    from traitlets.utils.descriptions import describe
ModuleNotFoundError: No module named 'traitlets.utils.descriptions'
```

See changelog: https://github.com/jupyter-server/jupyter_server/blob/main/CHANGELOG.md#1132
and the changing PR: https://github.com/jupyter-server/jupyter_server/pull/650

After downgrading to **1.13.1** I am able to start jupyterlab. Therefore the dependencies must be updated.

### Installed packages

```shell
# Name                    Version                   Build  Channel
anyio                     3.3.2            py36h79c6626_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
appnope                   0.1.3              pyhd8ed1ab_0    conda-forge
argon2-cffi               21.1.0           py36hfa26744_0    conda-forge
async_generator           1.10                       py_0    conda-forge
atk-1.0                   2.36.0               he69c4ee_4    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
babel                     2.10.3             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bleach                    5.0.0              pyhd8ed1ab_0    conda-forge
blosc                     1.21.1               h97e831e_3    conda-forge
brotlipy                  0.7.0           py36hfa26744_1001    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
c-ares                    1.18.1               h0d85af4_0    conda-forge
ca-certificates           2022.6.15            h033912b_0    conda-forge
cairo                     1.16.0            he43a7df_1008    conda-forge
certifi                   2021.5.30        py36h79c6626_0    conda-forge
cffi                      1.14.6           py36hbc36220_1    conda-forge
cfgv                      3.3.1              pyhd8ed1ab_0    conda-forge
chardet                   3.0.4           py36h2432673_1008    conda-forge
colorlog                  4.2.1            py36h9f0ad1d_0    conda-forge
contextvars               2.1                        py_0    conda-forge
cryptography              35.0.0           py36ha6a00b0_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cython                    0.29.24          py36hefe7e0e_0    conda-forge
dataclasses               0.8                pyh787bdff_2    conda-forge
dbus                      1.13.6               h811a1a6_3    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
distlib                   0.3.4              pyhd8ed1ab_0    conda-forge
docopt                    0.6.2                      py_1    conda-forge
editdistance-s            1.0.0            py36hc61eee1_1    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
epics-base                7.0.6.1              h20a6626_0    conda-forge
expat                     2.4.8                h96cf925_0    conda-forge
fftw                      3.3.10          nompi_hf082fe4_102    conda-forge
filelock                  3.4.1              pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.94              h10f422b_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.10.4               h4cff582_1    conda-forge
fribidi                   1.0.10               hbcb3906_0    conda-forge
future                    0.18.2           py36h79c6626_3    conda-forge
gdk-pixbuf                2.42.8               hb161b9c_0    conda-forge
gettext                   0.19.8.1          hd1a6beb_1008    conda-forge
ghostscript               9.54.0               h96cf925_2    conda-forge
giflib                    5.2.1                hbcb3906_2    conda-forge
gitdb                     4.0.9              pyhd8ed1ab_0    conda-forge
gitpython                 3.1.18             pyhd8ed1ab_0    conda-forge
graphite2                 1.3.13            h2e338ed_1001    conda-forge
graphviz                  2.50.0               h77de9ca_1    conda-forge
gtk2                      2.24.33              h675d97a_1    conda-forge
gts                       0.7.6                hccb3bdf_2    conda-forge
h5py                      2.10.0          nompi_py36h4d7a79e_106    conda-forge
harfbuzz                  3.1.1                h159f659_0    conda-forge
hdf5                      1.10.6          nompi_hc5d9132_1114    conda-forge
icu                       68.2                 he49afe7_0    conda-forge
identify                  2.3.7              pyhd8ed1ab_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagemagick               7.0.11_14       pl5320h3e49128_0    conda-forge
importlib-metadata        4.8.1            py36h79c6626_0    conda-forge
importlib_metadata        4.8.1                hd8ed1ab_1    conda-forge
importlib_resources       5.8.0              pyhd8ed1ab_0    conda-forge
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
ipykernel                 5.5.5            py36h495a4c6_0    conda-forge
ipython                   7.16.1           py36h9cf137f_2    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.6.5              pyhd8ed1ab_0    conda-forge
jbig                      2.1               h0d85af4_2003    conda-forge
jedi                      0.17.2           py36h79c6626_1    conda-forge
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h5eb16cf_1    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                4.1.2              pyhd8ed1ab_0    conda-forge
jupyter                   1.0.0            py36h79c6626_6    conda-forge
jupyter_client            7.1.2              pyhd8ed1ab_0    conda-forge
jupyter_console           6.4.3              pyhd8ed1ab_0    conda-forge
jupyter_core              4.8.1            py36h79c6626_0    conda-forge
jupyter_server            1.13.1             pyhd8ed1ab_0    conda-forge
jupyterlab                3.3.4              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.10.3             pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.1.0              pyhd8ed1ab_0    conda-forge
kiwisolver                1.3.1            py36hc61eee1_1    conda-forge
krb5                      1.19.3               hb49756b_0    conda-forge
lcms2                     2.12                 h577c468_0    conda-forge
lerc                      3.0                  he49afe7_0    conda-forge
libblas                   3.9.0           15_osx64_openblas    conda-forge
libcblas                  3.9.0           15_osx64_openblas    conda-forge
libclang                  11.1.0          default_he082bbe_1    conda-forge
libcurl                   7.83.1               h372c54d_0    conda-forge
libcxx                    14.0.5               hce7ea42_1    conda-forge
libdeflate                1.10                 h0d85af4_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgd                     2.3.3                h311d3fc_0    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_23    conda-forge
libgfortran5              9.3.0               h6c81a4c_23    conda-forge
libglib                   2.70.2               hf1fb8c0_4    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
liblapack                 3.9.0           15_osx64_openblas    conda-forge
libllvm10                 10.0.1               h009f743_3    conda-forge
libllvm11                 11.1.0               hd011deb_3    conda-forge
libnghttp2                1.47.0               h942079c_0    conda-forge
libopenblas               0.3.20          openmp_hb3cd9ec_0    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libpq                     13.5                 hea3049e_1    conda-forge
librsvg                   2.52.5               h02b643e_1    conda-forge
libsodium                 1.0.18               hbcb3906_1    conda-forge
libssh2                   1.10.0               h52ee1ee_2    conda-forge
libtiff                   4.3.0                hfca7e8f_4    conda-forge
libtool                   2.4.6             he49afe7_1008    conda-forge
libusb                    1.0.26             hc2f2c32_100    conda-forge
libwebp                   1.2.2                h28dabe5_0    conda-forge
libwebp-base              1.2.2                h0d85af4_1    conda-forge
libxcb                    1.13              h0d85af4_1004    conda-forge
libxml2                   2.9.12               h93ec3fd_0    conda-forge
libxslt                   1.1.33               h5739fc3_2    conda-forge
libzlib                   1.2.12               hfe4f2af_1    conda-forge
line_profiler             2.1.2           py36h0b31af3_1003    conda-forge
llvm-openmp               14.0.4               ha654fa7_0    conda-forge
llvmlite                  0.34.0           py36hdce38a9_2    conda-forge
lxml                      4.5.2            py36h796cb7d_1    conda-forge
lz4-c                     1.9.3                he49afe7_1    conda-forge
markupsafe                2.0.1            py36hfa26744_0    conda-forge
matplotlib                3.2.2                         1    conda-forge
matplotlib-base           3.2.2            py36h83d3ec1_1    conda-forge
mistune                   0.8.4           py36hfa26744_1004    conda-forge
mock                      4.0.3            py36h79c6626_1    conda-forge
more-itertools            8.13.0             pyhd8ed1ab_0    conda-forge
mysql-common              8.0.29               h924029e_1    conda-forge
mysql-libs                8.0.29               h3cab752_1    conda-forge
nbclassic                 0.3.5              pyhd8ed1ab_0    conda-forge
nbconvert                 5.6.1              pyhd8ed1ab_2    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  h96cf925_1    conda-forge
nest-asyncio              1.5.5              pyhd8ed1ab_0    conda-forge
netaddr                   0.7.19                     py_0    conda-forge
netifaces                 0.10.9          py36h20b66c6_1003    conda-forge
nodeenv                   1.6.0              pyhd8ed1ab_0    conda-forge
notebook                  6.3.0            py36h79c6626_0    conda-forge
nspr                      4.32                 hcd9eead_1    conda-forge
nss                       3.78                 ha8197d3_0    conda-forge
numba                     0.51.2           py36h72eec15_0    conda-forge
numexpr                   2.7.3            py36he43235d_0    conda-forge
numpy                     1.19.5           py36h08b5fde_2    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                h6e7aa92_1    conda-forge
openssl                   1.1.1o               hfe4f2af_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.1.5            py36h2be6da3_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
pango                     1.48.10              h056538c_2    conda-forge
parso                     0.7.1              pyh9f0ad1d_0    conda-forge
pcaspy                    0.7.3            py36h72eec15_0    conda-forge
pcre                      8.45                 he49afe7_0    conda-forge
pep8                      1.7.1                      py_0    conda-forge
perl                      5.32.1          2_h0d85af4_perl5    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    7.2.0            py36h79df3f4_2    conda-forge
pip                       20.2.4                     py_0    conda-forge
pixman                    0.40.0               hbcb3906_0    conda-forge
pkg-config                0.29.2            ha3d46e9_1008    conda-forge
pluggy                    1.0.0            py36h79c6626_1    conda-forge
pre-commit                2.7.1            py36h9f0ad1d_1    conda-forge
progressbar2              3.37.0                   py36_0    conda-forge
prometheus_client         0.14.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.29             pyha770c72_0    conda-forge
prompt_toolkit            3.0.29               hd8ed1ab_0    conda-forge
psutil                    5.7.3            py36ha3de816_0    conda-forge
psycopg2                  2.8.6            py36h32f7429_3    conda-forge
pthread-stubs             0.4               hc929b4f_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
py                        1.11.0             pyh6c4a22f_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyepics                   3.4.3            py36h79c6626_1    conda-forge
pyflakes                  2.2.0              pyh9f0ad1d_0    conda-forge
pygments                  2.12.0             pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyqt                      5.12.3           py36h79c6626_7    conda-forge
pyqt-impl                 5.12.3           py36hb40023b_7    conda-forge
pyqt5-sip                 4.19.18          py36h3ffa6ac_7    conda-forge
pyqtchart                 5.12             py36hb40023b_7    conda-forge
pyqtwebengine             5.12.1           py36hb40023b_7    conda-forge
pyrsistent                0.17.3           py36hfa26744_2    conda-forge
pyserial                  3.5                pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py36h79c6626_3    conda-forge
pytables                  3.6.1            py36h256c1cb_3    conda-forge
pytest                    6.2.5            py36h79c6626_0    conda-forge
pytest-runner             5.3.2              pyhd8ed1ab_0    conda-forge
python                    3.6.15          haf480d7_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-utils              3.3.3              pyhd8ed1ab_0    conda-forge
python_abi                3.6                     2_cp36m    conda-forge
pytz                      2020.5             pyhd8ed1ab_0    conda-forge
pyusb                     1.1.1              pyh44b312d_0    conda-forge
pyvisa                    1.10.1           py36h9f0ad1d_4    conda-forge
pyvisa-py                 0.5.1              pyh9f0ad1d_1    conda-forge
pyyaml                    5.4.1            py36hfa26744_1    conda-forge
pyzmq                     22.3.0           py36h50cd92c_0    conda-forge
qt                        5.12.9               h126340a_4    conda-forge
qtconsole                 5.2.2              pyhd8ed1ab_1    conda-forge
qtconsole-base            5.2.2              pyhd8ed1ab_1    conda-forge
qtpy                      2.0.1              pyhd8ed1ab_0    conda-forge
readline                  8.1.2                h3899abd_0    conda-forge
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
scipy                     1.5.3            py36h4f136de_1    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                58.0.4           py36h79c6626_2    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
smmap                     3.0.5              pyh44b312d_0    conda-forge
snakeviz                  2.0.1                      py_0    conda-forge
snappy                    1.1.9                h6e38e02_1    conda-forge
sniffio                   1.2.0            py36h79c6626_1    conda-forge
sqlite                    3.38.5               hd9f0692_0    conda-forge
stomp.py                  6.1.0              pyh9f0ad1d_0    conda-forge
terminado                 0.12.1           py36h79c6626_0    conda-forge
testpath                  0.6.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h5dbffcc_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tornado                   6.1              py36hfa26744_1    conda-forge
tqdm                      4.49.0             pyh9f0ad1d_0    conda-forge
traitlets                 4.3.3              pyhd8ed1ab_2    conda-forge
typing_extensions         4.1.1              pyha770c72_0    conda-forge
untangle                  1.1.1              pyh9f0ad1d_0    conda-forge
urllib3                   1.25.11                    py_0    conda-forge
virtualenv                20.4.7           py36h79c6626_0    conda-forge
vitables                  3.0.2            py36h9de38fb_1    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.3.1              pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
widgetsnbextension        3.5.1            py36h79c6626_4    conda-forge
xorg-kbproto              1.0.7             h35c211d_1002    conda-forge
xorg-libice               1.0.10               h0d85af4_0    conda-forge
xorg-libsm                1.2.3             h0d85af4_1000    conda-forge
xorg-libx11               1.7.2                h0d85af4_0    conda-forge
xorg-libxau               1.0.9                h35c211d_0    conda-forge
xorg-libxdmcp             1.1.3                h35c211d_0    conda-forge
xorg-libxext              1.3.4                h0d85af4_1    conda-forge
xorg-libxrender           0.9.10            h0d85af4_1003    conda-forge
xorg-libxt                1.2.1                h0d85af4_2    conda-forge
xorg-renderproto          0.11.1            h0d85af4_1002    conda-forge
xorg-xextproto            7.3.0             h35c211d_1002    conda-forge
xorg-xproto               7.0.31            h35c211d_1007    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
yaml                      0.2.5                h0d85af4_2    conda-forge
zeromq                    4.3.4                he49afe7_1    conda-forge
zipp                      3.6.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               hfe4f2af_1    conda-forge
zstd                      1.5.2                ha9df2e0_1    conda-forge
```

### Environment info

```shell
active environment : lab3
    active env location : /Users/Simon/miniconda3/envs/lab3
            shell level : 1
       user config file : /Users/Simon/.condarc
 populated config files : /Users/Simon/.condarc
          conda version : 4.13.0
    conda-build version : 3.21.9
         python version : 3.7.13.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/Simon/miniconda3  (writable)
      conda av data dir : /Users/Simon/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/Simon/miniconda3/pkgs
                          /Users/Simon/.conda/pkgs
       envs directories : /Users/Simon/miniconda3/envs
                          /Users/Simon/.conda/envs
               platform : osx-64
             user-agent : conda/4.13.0 requests/2.27.1 CPython/3.7.13 Darwin/20.6.0 OSX/10.16
                UID:GID : 502:20
             netrc file : None
           offline mode : False
```

**Comment by bollwyvl** [comment]
Python 3.6 is EOL, and you'll likely need to start pinning almost everything, as newer packages will all but never be tested by conda-forge directly.

We do the best we can, but keeping all the metadata accurate can be challenging. At this point it would take rather a lot of effort, and potential disruption to others who _have_ pinned to exact historical versions, to make this work properly for you.

**Comment by spreiter** [comment]
I see. So old _invalid_ information will stay in the database forever.

But I see that this would require a lot of effort for all packages.
